
server:
  port: 8086
  servlet:
    context-path: /demo

spring:
  resources:
    static-locations:
    - classpath:/static
    - classpath:/templates
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false
    mode: html
    encoding: utf-8
    servlet:
      content-type: text/html; charset=utf-8
#  datasource:
#      type: com.zaxxer.hikari.HikariDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/sakila?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
#      username: root
#      password: 123456
#      hikari:
#        auto-commit: true
#        connection-test-query: select 1
#        connection-timeout: 30000
#        idle-timeout: 600000
#        max-lifetime: 1800000
#        maximum-pool-size: 20
#        minimum-idle: 10
